on: 
  push:
    tags:
    - v*
name: build and release
jobs:
  release:
    name: tresor
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: checkout source
      uses: actions/checkout@master
    - name: build linux amd64
      run: |
        go build -v -o tresor_linux_amd64 main.go
        sha256sum tresor_linux_amd64 > tresor_linux_amd64.sha256
      env:
        GOARCH: amd64
        GOOS: linux
        CGO_ENABLED: 0
    - name: build linux arm64
      run: |
        go build -v -o tresor_linux_arm64 main.go
        sha256sum tresor_linux_arm64 > tresor_linux_arm64.sha256
      env:
        GOARCH: arm64
        GOOS: linux
        CGO_ENABLED: 0
    - name: build darwin amd64
      run: |
        go build -v -o tresor_darwin_amd64 main.go
        sha256sum tresor_darwin_amd64 > tresor_darwin_amd64.sha256
      env:
        GOARCH: amd64
        GOOS: darwin
        CGO_ENABLED: 0
    - name: build windows amd64
      run: |
        go build -v -o tresor_windows_amd64 main.go
        sha256sum tresor_windows_amd64 > tresor_windows_amd64.sha256
      env:
        GOARCH: amd64
        GOOS: windows
        CGO_ENABLED: 0
    - name: create release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: tresor-${{ github.ref }}
        draft: false
        prerelease: false
    - name: upload binary asset linux amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./tresor_linux_amd64
        asset_name: tresor_linux_amd64
        asset_content_type: application/octet-stream
    - name: upload binary checksum linux amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./tresor_linux_amd64.sha256
        asset_name: tresor_linux_amd64.sha256
        asset_content_type: text/plain
    - name: upload binary asset linux arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./tresor_linux_arm64
        asset_name: tresor_linux_arm64
        asset_content_type: application/octet-stream
    - name: upload binary checksum linux arm64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./tresor_linux_arm64.sha256
        asset_name: tresor_linux_arm64.sha256
        asset_content_type: text/plain

    - name: upload binary asset darwin amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./tresor_darwin_amd64
        asset_name: tresor_darwin_amd64
        asset_content_type: application/octet-stream
    - name: upload binary checksum darwin amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./tresor_darwin_amd64.sha256
        asset_name: tresor_darwin_amd64.sha256
        asset_content_type: text/plain
    - name: upload binary asset windows amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./tresor_windows_amd64
        asset_name: tresor_windows_amd64
        asset_content_type: application/octet-stream
    - name: upload binary checksum windows amd64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }}
        asset_path: ./tresor_windows_amd64.sha256
        asset_name: tresor_windows_amd64.sha256
        asset_content_type: text/plain

