on: 
  push:
    branches:
    - master
name: build and release
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: checkout source
      uses: actions/checkout@master
    - name: get dependencies
      run: |
        npm install github-release-cli
    - name: build
      run: |
        go build -v -o tresor_linux64 main.go
        sha256sum tresor_linux64 > tresor_linux64.sha256
      env:
        GOARCH: amd64
        GOOS: linux
        CGO_ENABLED: 0
    - name: create release
      id: release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release Linux x86_64 ${{ github.ref }}
        draft: false
        prerelease: false
    - name: upload release asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: ./tresor_linux64
        asset_name: tresor_linux64
        asset_content_type: application/octet-stream

