on: 
  push:
    branches:
    - master
name: build and release
jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: checkout source
      uses: actions/checkout@master
    - name: get dependencies
      run: |
        npm install github-release-cli
    - name: build
      run: |
        go build -v -o tresor_linux64 main.go
        sha256sum tresor_linux64 > tresor_linux64.sha256
      env:
        GOARCH: amd64
        GOOS: linux
        CGO_ENABLED: 0
    - name: release
      run: |
        ./node_modules/github-release-cli/bin/github-release upload --token "${GITHUB_TOKEN}" --owner helloworlddan --repo tresor --tag "linux-v${VERSION}" --name "tresor_linux64" --body "Current stable release for Linux 64-bit" tresor_linux64 tresor_linux64.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: 1.1.1

  release-darwin-amd64:
    name: release darwin/amd64
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: checkout source
      uses: actions/checkout@master
    - name: get dependencies
      run: |
        npm install github-release-cli
    - name: build
      run: |
        go build -v -o tresor_darwin64 main.go
        sha256sum tresor_darwin64 > tresor_darwin64.sha256
      env:
        GOARCH: amd64
        GOOS: darwin
        CGO_ENABLED: 0
    - name: release
      run: |
        ./node_modules/github-release-cli/bin/github-release upload --token "${GITHUB_TOKEN}" --owner helloworlddan --repo tresor --tag "darwin-v${VERSION}" --name "tresor_darwin64" --body "Current stable release for MacOS 64-bit" tresor_darwin64 tresor_darwin64.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: 1.1.1

  release-windows-amd64:
    name: release windows/amd64
    runs-on: ubuntu-latest
    steps:
    - name: setup go
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
    - name: checkout source
      uses: actions/checkout@master
    - name: get dependencies
      run: |
        npm install github-release-cli
    - name: build
      run: |
        go build -v -o tresor.exe main.go
        sha256sum tresor.exe > tresor.exe.sha256
      env:
        GOARCH: amd64
        GOOS: windows
        CGO_ENABLED: 0
    - name: release
      run: |
        ./node_modules/github-release-cli/bin/github-release upload --token "${GITHUB_TOKEN}" --owner helloworlddan --repo tresor --tag "windows-v${VERSION}" --name "tresor.exe" --body "Current stable release for Windows 64-bit" tresor.exe tresor.exe.sha256
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        VERSION: 1.1.1